//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevExtremeMvcApp1.Models.FuhrparkContext
{

    [NonPersistent]
    public partial class GetEinkaufIdResult
    {
        public int EinkaufId { get; set; }
        public decimal ListenpreisB { get; set; }
        public decimal EKPreisB { get; set; }
        public DateTime Erstzulassung { get; set; }
        public DateTime KMDatum { get; set; }
        public string KMStand { get; set; }
        public DateTime Kaufdatum { get; set; }
    }

}
