//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevExtremeMvcApp1.Models.FuhrparkContext
{

    [NonPersistent]
    public partial class GetIndexUebersichtResult
    {
        public int Id { get; set; }
        public string Kennzeichen { get; set; }
        public string Marke { get; set; }
        public string Modell { get; set; }
        public string Fahrzeughalter { get; set; }
        public string Niederlassung { get; set; }
        public string Kraftstoff { get; set; }
        public bool Neuwagen { get; set; }
        public string Status { get; set; }
    }

}
