//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevExtremeMvcApp1.Models.FuhrparkContext
{
    public static class SprocHelper
    {
        public static DevExpress.Xpo.DB.SelectedData ExecGetEinkaufId(Session session)
        {
            return session.ExecuteSproc("GetEinkaufId");
        }
        public static System.Collections.Generic.ICollection<GetEinkaufIdResult> ExecGetEinkaufIdIntoObjects(Session session)
        {
            return session.GetObjectsFromSproc<GetEinkaufIdResult>("GetEinkaufId");
        }
        public static XPDataView ExecGetEinkaufIdIntoDataView(Session session)
        {
            DevExpress.Xpo.DB.SelectedData sprocData = session.ExecuteSproc("GetEinkaufId");
            return new XPDataView(session.Dictionary, session.GetClassInfo(typeof(GetEinkaufIdResult)), sprocData);
        }
        public static void ExecGetEinkaufIdIntoDataView(XPDataView dataView, Session session)
        {
            DevExpress.Xpo.DB.SelectedData sprocData = session.ExecuteSproc("GetEinkaufId");
            dataView.PopulateProperties(session.GetClassInfo(typeof(GetEinkaufIdResult)));
            dataView.LoadData(sprocData);
        }
        public static DevExpress.Xpo.DB.SelectedData ExecGetIndexUebersicht(Session session)
        {
            return session.ExecuteSproc("GetIndexUebersicht");
        }
        public static System.Collections.Generic.ICollection<GetIndexUebersichtResult> ExecGetIndexUebersichtIntoObjects(Session session)
        {
            return session.GetObjectsFromSproc<GetIndexUebersichtResult>("GetIndexUebersicht");
        }
        public static XPDataView ExecGetIndexUebersichtIntoDataView(Session session)
        {
            DevExpress.Xpo.DB.SelectedData sprocData = session.ExecuteSproc("GetIndexUebersicht");
            return new XPDataView(session.Dictionary, session.GetClassInfo(typeof(GetIndexUebersichtResult)), sprocData);
        }
        public static void ExecGetIndexUebersichtIntoDataView(XPDataView dataView, Session session)
        {
            DevExpress.Xpo.DB.SelectedData sprocData = session.ExecuteSproc("GetIndexUebersicht");
            dataView.PopulateProperties(session.GetClassInfo(typeof(GetIndexUebersichtResult)));
            dataView.LoadData(sprocData);
        }
    }
}
