//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevExtremeMvcApp1.Models.FuhrparkContext
{

    public partial class uebersicht_daten : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fKennzeichen;
        [Size(10)]
        public string Kennzeichen
        {
            get { return fKennzeichen; }
            set { SetPropertyValue<string>(nameof(Kennzeichen), ref fKennzeichen, value); }
        }
        string fMarke;
        [Size(10)]
        public string Marke
        {
            get { return fMarke; }
            set { SetPropertyValue<string>(nameof(Marke), ref fMarke, value); }
        }
        string fModell;
        [Size(10)]
        public string Modell
        {
            get { return fModell; }
            set { SetPropertyValue<string>(nameof(Modell), ref fModell, value); }
        }
        string fFahrzeughalter;
        [Size(10)]
        public string Fahrzeughalter
        {
            get { return fFahrzeughalter; }
            set { SetPropertyValue<string>(nameof(Fahrzeughalter), ref fFahrzeughalter, value); }
        }
        string fNiederlassung;
        [Size(10)]
        public string Niederlassung
        {
            get { return fNiederlassung; }
            set { SetPropertyValue<string>(nameof(Niederlassung), ref fNiederlassung, value); }
        }
        string fKraftstoff;
        [Size(10)]
        public string Kraftstoff
        {
            get { return fKraftstoff; }
            set { SetPropertyValue<string>(nameof(Kraftstoff), ref fKraftstoff, value); }
        }
        bool fNeuwagen;
        [ColumnDbDefaultValue("((0))")]
        public bool Neuwagen
        {
            get { return fNeuwagen; }
            set { SetPropertyValue<bool>(nameof(Neuwagen), ref fNeuwagen, value); }
        }
        string fStatus;
        [Size(SizeAttribute.Unlimited)]
        public string Status
        {
            get { return fStatus; }
            set { SetPropertyValue<string>(nameof(Status), ref fStatus, value); }
        }
    }

}
